Finish mobile portfolio
joramot/portfolio pull request #2
Opened 2023-01-12 16:51 UTC by joramot

- Add Works section.
- Add About Me section.
- Use Flexbox and CSS Grid in both sections.

2023-01-12 18:37 UTC, binhussen requested changes
Hi @joramot , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Required Changes ♻️
- Kindly use semantic tags for readability and search engines. 👌😁
- kindly stick to the figma design with font, and color background... 👌

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 18:37 UTC, binhussen commented on index.html
>              </ul>
- Great job for using `ul`, `li`, and `a`, I think is better to re-arrange them for semantic reasons 👌😁
```
<ul>
   <li>
      <a>
      </a>
   </li>
</ul>
```

2023-01-12 18:37 UTC, binhussen commented on index.html
> +            </ul>
- Great job for using `ul`, `li`, and `a`, I think is better to re-arrange them for semantic reasons 👌😁
```
<ul>
   <li>
      <a>
      </a>
   </li>
</ul>
```

2023-01-12 18:37 UTC, binhussen commented on index.html
> +            </ul>
- Great job for using `ul`, `li`, and `a`, I think is better to re-arrange them for semantic reasons 👌😁
```
<ul>
   <li>
      <a>
      </a>
   </li>
</ul>
```

2023-01-12 18:37 UTC, binhussen commented on index.html
> +            </ul>
- Great job for using `ul`, `li`, and `a`, I think is better to re-arrange them for semantic reasons 👌😁
```
<ul>
   <li>
      <a>
      </a>
   </li>
</ul>
```

2023-01-12 18:37 UTC, binhussen commented on index.html
> +            </ul>
- Great job for using `ul`, `li`, and `a`, I think is better to re-arrange them for semantic reasons 👌😁
```
<ul>
   <li>
      <a>
      </a>
   </li>
</ul>
```

2023-01-12 18:37 UTC, binhussen commented on index.html
> +            </ul>
- Great job for using `ul`, `li`, and `a`, I think is better to re-arrange them for semantic reasons 👌😁
```
<ul>
   <li>
      <a>
      </a>
   </li>
</ul>
```

2023-01-12 18:37 UTC, binhussen commented on index.html
> +          </ul>
- Great job for using `ul`, `li`, I think is better to use `a` inside `li` for user interactivity👌😁
like this
```
<ul>
   <li>
      <a>
      </a>
   </li>
</ul>
```

2023-01-12 18:37 UTC, binhussen commented on index.html
> +          </ul>
- Great job for using `ul`, `li`, I think is better to use `a` inside `li` for user interactivity👌😁
like this
```
<ul>
   <li>
      <a>
      </a>
   </li>
</ul>
```

2023-01-12 18:37 UTC, binhussen commented on index.html
> +          </ul>
- Great job for using `ul`, `li`, I think is better to use `a` inside `li` for user interactivity👌😁
like this
```
<ul>
   <li>
      <a>
      </a>
   </li>
</ul>
```

2023-01-12 18:37 UTC, binhussen commented on index.html
> +            <img class="icons-skills" src="/images/circle.png" alt="">
- Kindly use `./` when you access images from the current directory not `/`, because it is not accessible on some environment 😁👌

2023-01-12 18:37 UTC, binhussen commented on css/style.css
> +}
- Kindly use `display: grid` for displaying the works container as the [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md) becouse it will help you later for desktop responsibility 👌👌

2023-01-12 18:37 UTC, binhussen commented on index.html
> +            </p>
- Kindly be sure that the whole section uses the font and colours (background and font) defined for the template 👌😁 here is your list of tech list is using the default `a` color update it with the Figma collor 👌👌

2023-01-12 20:43 UTC, joramot commented on index.html
> +            </p>
Hi @binhussen, thanks, in this point I don't understand what I need to change, the color and type font is the same as Figma, can you give me more information? please.

2023-01-12 21:08 UTC, joramot commented on css/style.css
> +}
hello @binhussen thanks for this comment I checked the requirement list and say: "Use CSS Grid in the main container that contains all of the cards and use Flexbox to lay out an individual card" and I am following that indication the class name of container cards is "works-area-cards" and I am applying CSS Grid, please kindly check it and give your new comment.

2023-01-12 21:09 UTC, joramot commented on index.html
> +          </ul>
I did it.

2023-01-12 21:09 UTC, joramot commented on index.html
>              </ul>
I did it.

2023-01-12 21:09 UTC, joramot commented on index.html
> +            </ul>
I did it.

2023-01-12 21:09 UTC, joramot commented on index.html
> +            </ul>
I did it.

2023-01-12 21:10 UTC, joramot commented on index.html
> +            </ul>
I did it.

2023-01-12 21:10 UTC, joramot commented on index.html
> +            </ul>
I did it.

2023-01-12 21:10 UTC, joramot commented on index.html
> +            </ul>
I did it.

2023-01-12 21:10 UTC, joramot commented on index.html
> +          </ul>
I did it.

2023-01-12 21:10 UTC, joramot commented on index.html
> +          </ul>
I did it.

2023-01-12 21:10 UTC, joramot commented on index.html
> +          </ul>
I did it.

2023-01-12 21:11 UTC, joramot commented on index.html
> +            <img class="icons-skills" src="/images/circle.png" alt="">
thanks, I did it.

2023-01-12 21:59 UTC, joramot reviewed
Changes the order <ul>, <li> and <a> tags in order to correct the readability and according to the search engines.
I used CSS Grid in the works container, I applied CSS Grid in the Works Cards container according to the requirement list.
Please, kindly can you help me?

2023-01-12 23:30 UTC, AbayomiOlaoye requested changes
Hi @joramot :clap: , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't being addressed yet.

![so_close](https://user-images.githubusercontent.com/99715640/211872359-9a4d36f7-0386-4000-82a4-c274b06a5ce4.gif)


 ## Highlights
- Good PR message ✅ 
- Great commit messages ✅ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 23:30 UTC, AbayomiOlaoye commented on index.html
> +                    </div>
- This is what I see in all of this: :point_down: 

![image](https://user-images.githubusercontent.com/99715640/212198562-68a30770-c731-4a4f-9934-6d87d44de27a.png)

- As against the figma design:
![image](https://user-images.githubusercontent.com/99715640/212198991-52444d2d-7bfd-484c-8094-3a0100222d12.png)

- [ ] Please consider reconciling these variances:
 - [ ] Nothing is showing
 - [ ] Your `background-image` is not displaying on all of your project cards and this is because of a bug in your file paths. Please consider implementing the previous reviewer's suggestion where he advised you to load your images from CSS using this syntax: e.g. `background-image: url(./images/cards-work-image.png);` 
 - [ ] Please be careful to include a period `.` before `/images..../...`  so that your images can load correctly.
 - [ ] The button is not looking really good now, please use the specifications provided by the figma template.

2023-01-12 23:30 UTC, AbayomiOlaoye commented on index.html
> +            <hr class="vector-about-me">
- [ ] [OPTIONAL] It's good that you used a `heading` tag here except that for SEO reasons and accessibility purposes for challenged persons, it's good to always have just one `h1` in your code base. You could use any other `hx` tag since it spans through 6.
- `h1`  shows the most important subject of a page, and clearly, you don't want this to be :smile: 
- [ ] Since we have discovered the bug introduced by broken `background-images` URLs, please consider working on implementing the background image that is currently missing from your design:
![image](https://user-images.githubusercontent.com/99715640/212201354-41b71358-205b-4c0f-ac53-e1df248bf33f.png)
- [ ] Figma design
![image](https://user-images.githubusercontent.com/99715640/212201200-740cc1e9-b4be-448b-9d82-e69309a16d7b.png)

- [ ] As a requirement, please let's make the button and the `images` be as it is above in the Figma design.

2023-01-12 23:30 UTC, AbayomiOlaoye commented on index.html
> +                    </div>
- I see that you tried loading some images here but it appears none works :point_down: 
![image](https://user-images.githubusercontent.com/99715640/212201993-78e4eef6-8a62-4732-8610-999ddbee2c93.png)

![image](https://user-images.githubusercontent.com/99715640/212202047-201ace0a-778f-4dbc-a4b4-e65fb4e5f428.png)

- [ ] Requirement looks like :point_down: :point_down: on Figma:
![image](https://user-images.githubusercontent.com/99715640/212202190-4c391fc0-db37-4356-876c-72b31cdd390e.png)
- [ ] Like the previous reviewer asked, please kindly our propositions on making this work. Consider including a period (.) sign in the file path just before image. :grey_question: 
- [ ] [OPTIONAL] Kindly add texts that describe your image in the `alt` attribute of your `img` tag. This improves your site's accessibility and interactivity.

2023-01-13 19:48 UTC, joramot commented on index.html
> +                    </div>
thank @AbayomiOlaoye I tried to use a dot in the background-images: URL path but the image does not show, I only wrap the path between  "" and it worked well.

2023-01-13 19:49 UTC, joramot commented on index.html
> +            <hr class="vector-about-me">
I did the changes and it ok now

2023-01-13 19:51 UTC, joramot commented on index.html
> +                    </div>
the same problem with the path definition, I fixed and it ok now.

2023-01-13 19:51 UTC, joramot commented on index.html
> +                    <button class="button-see-project button" type="button">See Project</button>
ok, thank

2023-01-13 21:40 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @joramot , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://camo.githubusercontent.com/af3e249aed483b04a88ff676e872d6926cd426af8a3e008290d32ec69f576ae9/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f69337133367a454653684331386f533676302f67697068792e676966" />

## Highlights :heavy_check_mark: 
- [x] Implemented all requested changes from the previous reviewer :heavy_check_mark: 
- [x] All linter checks are set up and passing with green check marks :heavy_check_mark: 
- [x] GitHub flow is used correctly :heavy_check_mark: 
- [ ] Professional readme file :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 20:17 UTC, joramot commented
Build the contact form in the contact section:
- Define all inputs according to the requirement list project.
- Implement formspree service to collect data from the form.
- Implement UX rules in the input elements in the form to help user complete each one correctly.

Add footer section to the media's icons bar .

2023-01-17 20:32 UTC, NahnahAJ reviewed
Hi @joramot , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is in the wrong feature branch. This is the branch you used for the finish mobile portfolio and since this is a new feature / milestone, you needed to first
1. Merge this branch into main after you got approval
2. Create a new feature branch from main with the name of the branch as the new feature you're implmenting.
3. Checkout to that branch on VS code and  push all your changes to the new branch
4. After this you can create a new pull request from that branch which wont have any of the previous interactions you had in this PR. Then you submit the new PR link for review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-17 20:45 UTC, closed without merging